default_platform(:ios)

platform :ios do
  desc "Upload to TestFlight"
  lane :upload_to_testflight_lane do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true,
      duration: 1200,
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: ENV["IPA_PATH"] || "./build/app.ipa",
      skip_waiting_for_build_processing: true,
      skip_submission: false,
      distribute_external: false,
    )
  end
end
